### ISSUE TITLE
Socket transports now throw IllegalArgumentException due to new OkHttp changes (ws/wss not allowd)

### ISSUE THREAD

**Issue by VicV** [nkzawa/engine.io-client.java#19]
Context: https://github.com/square/okhttp/issues/1652

Specific lines that touch each other:

This part creates a URL with the ws/wss:// scheme:
https://github.com/nkzawa/engine.io-client.java/blob/master/src/main/java/com/github/nkzawa/engineio/client/transports/WebSocket.java#L194

This disallows that:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L880

I believe Square will eventually make changes to fix this. However, in the meantime, stick to OkHttp 2.3.0 to avoid this problem.

**Comment by nkzawa** [comment]
Thanks for your report!!! It looks the issue was fixed on 2.4.0? All our tests passed somehow.

https://travis-ci.org/nkzawa/engine.io-client.java
https://github.com/nkzawa/engine.io-client.java/pull/20

**Comment by VicV** [comment]
Yep! all cleared up in 2.4.0

**Comment by b95505017** [comment]
This issue only existed in OkHttp 2.4.0-RC1?
But engine.io-client only using okhttp-ws 2.3 & 2.4, so it shouldn't be a issue, right?

**Comment by VicV** [comment]
Yep.

**Comment by nkzawa** [comment]
Released as 0.5.1

**Comment by voidstarfire** [comment]
Is this possibly related to https://github.com/robovm/robovm/issues/1153
