### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by fatihsokmen** [nkzawa/engine.io-client.java#28]
Exception at class com.github.nkzawa.engineio.client.transports.PollingXHR

Reason: Enumerating String value causes classcastexception at line 192 (tag **0.6.0**).

Code changes;
from (**0.5.1**)

            self.onRequestHeaders(headers);
            for (Map.Entry<String, String> header : headers.entrySet()) {
                xhr.setRequestProperty(header.getKey(), header.getValue());
            }

to (**0.6.0**)

            self.onRequestHeaders(headers);
            for (Map.Entry<String, List<String>> header : headers.entrySet()) {
                for (String v : header.getValue()){
                    xhr.addRequestProperty(header.getKey(), v);
                }
            }

**Comment by nkzawa** [comment]
Yes, there was a backward incompatible change on v0.6.0.
Can you post your code if you are setting http headers ?

**Comment by fatihsokmen** [comment]
In my case, I am listening transport event and setting authorization header on every request.

Setting up Socket.io client

	IO.Options opts = new IO.Options();
	opts.secure = true;
	opts.forceNew = true;
	opts.reconnection = false;

	socket = IO.socket("https://remoty.io:443", opts);
	socket.io().on(Manager.EVENT_TRANSPORT, onTransport);


And, setting auth header on every onTransport event handler.

	private Emitter.Listener onTransport = new Emitter.Listener() {
	    @Override
	    public void call(Object... args) {

	        Transport transport = (Transport)args[0];
	        transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
	            @Override
	            public void call(Object... args) {
	                @SuppressWarnings("unchecked")
	                Map<String, String> headers = (Map<String, String>)args[0];
	                if (session != null) {
	                    headers.put("Authorization","bearer " + session.token);
	                }
	            }
	        }).on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
	            @Override
	            public void call(Object... args) {
	            }
	        });
	    }
	};

**Comment by nkzawa** [comment]
@fatihsokmen please update your code like the doc https://github.com/nkzawa/engine.io-client.java#extra-features-only-for-java-client.

`headers` type has to be `Map<String, List<String>>` from v06.0.

**Comment by fatihsokmen** [comment]
I am not sure what is wrong with version 0.6.0. Authorization header doesn't work in this way. I am getting bad format error with the following snippet. Any idea ?

    private Emitter.Listener onTransport = new Emitter.Listener() {
        @Override
        public void call(Object... args) {

            Transport transport = (Transport)args[0];
            transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    @SuppressWarnings("unchecked")
                    Map<String, List<String>> headers = (Map<String, List<String>>) args[0];
                    if (session != null) {
                        String bearer = "bearer  " + session.token;
                        headers.put("Authorization", Arrays.asList(bearer));
                    }
                }
            }).on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                }
            });
        }
    };

{
     "message":"Format is Authorization: Bearer [token]", 
     "code":"credentials_bad_format",
     "type":"UnauthorizedError"
}

**Comment by fatihsokmen** [comment]
My fault. Double space after 'bearer' string. We may close this issue.
Thanks for your effort.
